sudo: required

services:
  - docker

before_install:
- docker build -t protoc-gen-flow .

script:
- docker run --rm -it -v `pwd`:/opt/protoc-gen-flow -v /opt/protoc-gen-flow/node_modules protoc-gen-flow make test
